-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 15:04:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `username` VARCHAR(45) NOT NULL COMMENT 'Username',
  `password` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `secondName` VARCHAR(45) NOT NULL,
  `isActive` TINYINT NOT NULL,
  `lastConnection` DATETIME NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TimeControl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TimeControl` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TimeControl` (
  `id_time_control` INT NOT NULL,
  `generated_date` DATETIME NOT NULL,
  `expired_date` DATETIME NOT NULL,
  PRIMARY KEY (`id_time_control`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MobileInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MobileInfo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MobileInfo` (
  `id_mobile_info` INT NOT NULL,
  `mobile_ip` VARCHAR(45) NOT NULL,
  `mobile_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_mobile_info`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Authentication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Authentication` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Authentication` (
  `id_authentication` INT NOT NULL,
  `user_token` VARCHAR(45) NOT NULL,
  `id_user` VARCHAR(45) NOT NULL,
  `id_control_time` INT NOT NULL,
  `id_mobile_info` INT NOT NULL,
  PRIMARY KEY (`id_authentication`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_control_time_idx` (`id_control_time` ASC) VISIBLE,
  INDEX `id_mobile_info_idx` (`id_mobile_info` ASC) VISIBLE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_control_time`
    FOREIGN KEY (`id_control_time`)
    REFERENCES `mydb`.`TimeControl` (`id_time_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_mobile_info`
    FOREIGN KEY (`id_mobile_info`)
    REFERENCES `mydb`.`MobileInfo` (`id_mobile_info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `id_products` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `photo_url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_products`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProductList` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProductList` (
  `id_product_list` INT NOT NULL,
  `id_product` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id_product_list`, `id_product`),
  INDEX `id_product_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `mydb`.`Products` (`id_products`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Car` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Car` (
  `id_car` INT NOT NULL,
  `id_user` VARCHAR(45) NOT NULL,
  `id_product_list` INT NOT NULL,
  PRIMARY KEY (`id_car`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_product_list_idx` (`id_product_list` ASC) VISIBLE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_product_list`
    FOREIGN KEY (`id_product_list`)
    REFERENCES `mydb`.`ProductList` (`id_product_list`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inventory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `id_inventory` INT NOT NULL,
  `id_product` INT NOT NULL,
  `stock_quantity` INT ZEROFILL NOT NULL,
  `sold_quantity` INT ZEROFILL NOT NULL,
  `freeze_quantity` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`id_inventory`),
  INDEX `id_product_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `mydb`.`Products` (`id_products`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Payment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `id_payment` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `message_id_nequi` VARCHAR(45) NOT NULL,
  `client_id_nequi` VARCHAR(45) NOT NULL,
  `phone_number_nequi` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_payment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `id_order` INT NOT NULL,
  `id_user` VARCHAR(45) NOT NULL,
  `id_product_list` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `id_payment` INT NOT NULL,
  PRIMARY KEY (`id_order`, `id_user`),
  INDEX `id_users_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_product_list_idx` (`id_product_list` ASC) VISIBLE,
  INDEX `id_payment_idx` (`id_payment` ASC) VISIBLE,
  CONSTRAINT `id_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_product_list`
    FOREIGN KEY (`id_product_list`)
    REFERENCES `mydb`.`ProductList` (`id_product_list`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_payment`
    FOREIGN KEY (`id_payment`)
    REFERENCES `mydb`.`Payment` (`id_payment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
